---

- hosts: default
  tasks:
    - ansible.builtin.fail:
        msg: Please configure 'provisioning/credentials.yml'
      when: (username is undefined or password is undefined) or
            (username == "username" or password == "password")

    - name: Install commonly useful packages
      become: true
      community.general.zypper:
        name:
          - man
        state: present

    - name: Install packages for the OBS local environment
      become: true
      community.general.zypper:
        name:
          - osc
          - build
          - obs-service-*
    
    - name: Configure osc
      block:
        - ansible.builtin.file:
            path: /home/vagrant/.config/osc/
            state: directory
            recurse: yes
            mode: 0700
        - ansible.builtin.template:
            src: home/vagrant/.config/osc/oscrc.j2
            dest: /home/vagrant/.config/osc/oscrc
